### ISSUE TITLE
Audio?

### ISSUE THREAD

**Issue by hkchengrex** [NJU-PCALab/OpenVid-1M#2]
Hello, congrats on the amazing work here! The video qualities are outstanding.

I noticed that the videos do not come with audio. Would it be possible for the team to upload the audio to huggingface as well? It would be immensely helpful to audio-visual research, and should only have a small impact on file sizes. 

Cheers.

**Comment by nankepan** [comment]
> Hello, congrats on the amazing work here! The video qualities are outstanding.
> 
> I noticed that the videos do not come with audio. Would it be possible for the team to upload the audio to huggingface as well? It would be immensely helpful to audio-visual research, and should only have a small impact on file sizes.
> 
> Cheers.

Thank you for your attention.
During the dataset construction process, we discarded the audio of most videos to improve collection efficiency and reduce the dataset's storage space. Unfortunately, re-collecting the audio for the dataset is a major task and could incur significant costs. However, this issue is important, and we will consider it in our future plans.

**Comment by hkchengrex** [comment]
Thank you for the detailed response! I see, that's unfortunate. I am looking forward to your future datasets!

**Comment by WangWenhao0716** [comment]
> Hello, congrats on the amazing work here! The video qualities are outstanding.
> 
> I noticed that the videos do not come with audio. Would it be possible for the team to upload the audio to huggingface as well? It would be immensely helpful to audio-visual research, and should only have a small impact on file sizes.
> 
> Cheers.

We plan to release a dataset with audio. Please see the update here: https://huggingface.co/datasets/WenhaoWang/VideoUFO
